root_url: "http://localhost:3000"
mailer_email_email: "YourAccount@gmail.com"
mailer_email_password: "YourGmailPassword"

db_database: "invitable_development"
db_username: "postgres"
db_password: "YourPostgresPassword"
db_host: "localhost"
db_port: "5432"

db_database_test: "invitable_test"
db_username_test: "postgres"
db_password_test: "YourPostgresPassword"
db_host_test: "localhost"
db_port_test: "5432"